package com.PIPPIP5789.mfrex.betterwithfantasy.init;

import betterwithaddons.BetterWithAddons;
import betterwithaddons.block.ModBlocks;
import betterwithaddons.crafting.recipes.AdobeRecipe;
import betterwithaddons.item.ModItems;
import betterwithmods.common.BWMBlocks;
import betterwithmods.common.BWMItems;
import betterwithmods.common.BWRegistry;
import betterwithmods.common.items.ItemMaterial;
import betterwithmods.common.registry.block.recipe.IngredientSpecial;
import betterwithmods.util.StackIngredient;
import com.PIPPIP5789.mfrex.core.util.RecipeIniter;
import com.google.common.collect.Lists;
import minefantasy.mfr.init.MineFantasyItems;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemFood;
import net.minecraft.item.ItemStack;
import net.minecraft.item.crafting.IRecipe;
import net.minecraft.item.crafting.Ingredient;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.eventhandler.EventPriority;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.oredict.OreIngredient;

public class BetterWithFantasyRecipeInit extends RecipeIniter {

    public static void registerBWMRecipes() {
        BWRegistry.CAULDRON.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromItem(MineFantasyItems.GENERIC_MEAT_CHUNK_COOKED), Ingredient.fromItem(Items.BOWL)), new ItemStack(MineFantasyItems.STEW));
        BWRegistry.CAULDRON.addUnstokedRecipe(Lists.newArrayList(new OreIngredient("meatFish"), Ingredient.fromItem(MineFantasyItems.JUG_MILK), Ingredient.fromStacks(StackIngredient.fromStacks(new ItemStack(Items.BOWL, 2)).getMatchingStacks()[0])), new ItemStack(BWMItems.CHOWDER, 2));
        BWRegistry.CAULDRON.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromItem(Items.WHEAT), Ingredient.fromItem(MineFantasyItems.JUG_MILK), Ingredient.fromItem(Items.WHEAT_SEEDS), Ingredient.fromItem(Items.BOWL)), new ItemStack(MineFantasyItems.OATS));
        BWRegistry.CAULDRON.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromItem(MineFantasyItems.COCA_POWDER), Ingredient.fromItem(MineFantasyItems.JUG_MILK), Ingredient.fromItem(MineFantasyItems.SUGAR_POT), Ingredient.fromItem(MineFantasyItems.CLAY_POT)), new ItemStack(MineFantasyItems.CHOCOLATE));
        BWRegistry.CAULDRON.addUnstokedRecipe(Lists.newArrayList(StackIngredient.fromStacks(new ItemStack(Item.getItemFromBlock(Blocks.BROWN_MUSHROOM), 3)), Ingredient.fromItem(MineFantasyItems.JUG_MILK), Ingredient.fromItem(Items.BOWL)), new ItemStack(Items.MUSHROOM_STEW));
        BWRegistry.CAULDRON.addUnstokedRecipe(Lists.newArrayList(StackIngredient.fromItem(MineFantasyItems.GENERIC_MEAT_COOKED), Ingredient.fromItem(MineFantasyItems.FLOUR), new OreIngredient("cookedCarrot"), new OreIngredient("cookedPotato"), StackIngredient.fromStacks(new ItemStack(Item.getItemFromBlock(Blocks.BROWN_MUSHROOM), 3)), StackIngredient.fromStacks(new ItemStack(Items.BOWL, 5))), new ItemStack(BWMItems.HEARTY_STEW, 5));

        BWRegistry.MILLSTONE.addMillRecipe(Lists.newArrayList(Ingredient.fromItem(Items.COAL), Ingredient.fromItem(MineFantasyItems.CLAY_POT)), Lists.newArrayList(new ItemStack(MineFantasyItems.COAL_DUST, 1)));
        BWRegistry.MILLSTONE.addMillRecipe(Lists.newArrayList(Ingredient.fromItem(MineFantasyItems.KAOLINITE), Ingredient.fromItem(MineFantasyItems.CLAY_POT)), Lists.newArrayList(new ItemStack(MineFantasyItems.KAOLINITE_DUST, 1)));
        BWRegistry.MILLSTONE.addMillRecipe(Lists.newArrayList(Ingredient.fromItem(MineFantasyItems.FLUX), Ingredient.fromItem(MineFantasyItems.CLAY_POT)), Lists.newArrayList(new ItemStack(MineFantasyItems.FLUX_POT, 1)));
        BWRegistry.MILLSTONE.addMillRecipe(Lists.newArrayList(Ingredient.fromItem(MineFantasyItems.GENERIC_MEAT_UNCOOKED), Ingredient.fromItem(MineFantasyItems.CLAY_POT)), Lists.newArrayList(new ItemStack(MineFantasyItems.GENERIC_MEAT_MINCE_UNCOOKED, 1)));
        BWRegistry.MILLSTONE.addMillRecipe(Lists.newArrayList(Ingredient.fromItem(MineFantasyItems.GENERIC_MEAT_STRIP_UNCOOKED), Ingredient.fromItem(MineFantasyItems.CLAY_POT)), Lists.newArrayList(new ItemStack(MineFantasyItems.GENERIC_MEAT_MINCE_UNCOOKED, 1)));
        BWRegistry.MILLSTONE.addMillRecipe(Lists.newArrayList(Ingredient.fromItem(MineFantasyItems.GENERIC_MEAT_CHUNK_UNCOOKED), Ingredient.fromItem(MineFantasyItems.CLAY_POT)), Lists.newArrayList(new ItemStack(MineFantasyItems.GENERIC_MEAT_MINCE_UNCOOKED, 1)));
        BWRegistry.MILLSTONE.addMillRecipe(Lists.newArrayList(Ingredient.fromItem(MineFantasyItems.GENERIC_MEAT_COOKED), Ingredient.fromItem(MineFantasyItems.CLAY_POT)), Lists.newArrayList(new ItemStack(MineFantasyItems.GENERIC_MEAT_MINCE_COOKED, 1)));
        BWRegistry.MILLSTONE.addMillRecipe(Lists.newArrayList(Ingredient.fromItem(MineFantasyItems.GENERIC_MEAT_STRIP_COOKED), Ingredient.fromItem(MineFantasyItems.CLAY_POT)), Lists.newArrayList(new ItemStack(MineFantasyItems.GENERIC_MEAT_MINCE_COOKED, 1)));
        BWRegistry.MILLSTONE.addMillRecipe(Lists.newArrayList(Ingredient.fromItem(MineFantasyItems.GENERIC_MEAT_CHUNK_COOKED), Ingredient.fromItem(MineFantasyItems.CLAY_POT)), Lists.newArrayList(new ItemStack(MineFantasyItems.GENERIC_MEAT_MINCE_COOKED, 1)));
        BWRegistry.MILLSTONE.addMillRecipe(Lists.newArrayList(Ingredient.fromItem(Items.WHEAT), Ingredient.fromItem(MineFantasyItems.CLAY_POT)), Lists.newArrayList(new ItemStack(MineFantasyItems.FLOUR, 1)));
        BWRegistry.MILLSTONE.addMillRecipe(Lists.newArrayList(Ingredient.fromItem(Items.BREAD), Ingredient.fromItem(MineFantasyItems.CLAY_POT)), Lists.newArrayList(new ItemStack(MineFantasyItems.BREADCRUMBS, 1)));
        BWRegistry.MILLSTONE.addMillRecipe(Lists.newArrayList(Ingredient.fromItem(Items.REEDS), Ingredient.fromItem(MineFantasyItems.CLAY_POT)), Lists.newArrayList(new ItemStack(MineFantasyItems.SUGAR_POT, 1)));
        BWRegistry.MILLSTONE.addMillRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 3)), Ingredient.fromItem(MineFantasyItems.CLAY_POT)), Lists.newArrayList(new ItemStack(MineFantasyItems.COCA_POWDER, 1)));

        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromItem(Items.SLIME_BALL), Ingredient.fromStacks(new ItemStack(Blocks.BROWN_MUSHROOM, 8))), new ItemStack(ModItems.MATERIAL_CONGEALED, 1, 4));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromItem(Items.SLIME_BALL), Ingredient.fromStacks(new ItemStack(Blocks.RED_MUSHROOM, 8))), new ItemStack(ModItems.MATERIAL_CONGEALED, 1, 3));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromItem(Items.SLIME_BALL), Ingredient.fromStacks(new ItemStack(Items.BONE, 8))), new ItemStack(ModItems.MATERIAL_CONGEALED, 1, 0));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromItem(Items.SLIME_BALL), Ingredient.fromStacks(new ItemStack(Items.ROTTEN_FLESH, 8))), new ItemStack(ModItems.MATERIAL_CONGEALED, 1, 1));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromItem(Items.SLIME_BALL), Ingredient.fromStacks(new ItemStack(Items.SPIDER_EYE, 8))), new ItemStack(ModItems.MATERIAL_CONGEALED, 1, 2));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromItem(Items.SLIME_BALL), Ingredient.fromStacks(new ItemStack(Blocks.NETHER_WART, 8))), new ItemStack(ModItems.MATERIAL_CONGEALED, 1, 5));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromItem(Item.getItemFromBlock(Blocks.BROWN_MUSHROOM)), Ingredient.fromItem(Item.getItemFromBlock(Blocks.RED_MUSHROOM)), Ingredient.fromItem(Item.getItemFromBlock(Blocks.MYCELIUM)), Ingredient.fromItem(Item.getItemFromBlock(Blocks.NETHER_WART)), Ingredient.fromItem(Items.ROTTEN_FLESH), Ingredient.fromStacks(new ItemStack(BWMBlocks.URN, 8, 8))), new ItemStack(BWMBlocks.NETHER_GROWTH, 1));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(BWMItems.MATERIAL, 1, 16)), Ingredient.fromStacks(new ItemStack(BWMItems.MATERIAL, 1, 21))), new ItemStack(BWMItems.MATERIAL, 1, 35));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(new OreIngredient("dustCarbon"), Ingredient.fromStacks(new ItemStack(BWMItems.MATERIAL, 1, 16))), new ItemStack(BWMItems.MATERIAL, 4, 1));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(BWMItems.MATERIAL, 1, 16)), Ingredient.fromStacks(new ItemStack(BWMItems.MATERIAL, 1, 13))), new ItemStack(BWMItems.MATERIAL, 2, 29));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(BWMItems.MATERIAL, 8, 16))), new ItemStack(BWMItems.MATERIAL, 1, 17));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromItem(Item.getItemFromBlock(Blocks.CACTUS))), new ItemStack(Items.DYE, 1, 2));
        //BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromItem(Items.REDSTONE), Ingredient.fromItem(Items.GLOWSTONE_DUST), Ingredient.fromStacks(new ItemStack(BWMBlocks.HEMP, 1, 3))), new ItemStack(BWMItems.MATERIAL, 1, 19));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(StackIngredient.fromStacks(ItemMaterial.getMaterial(ItemMaterial.EnumMaterial.SCOURED_LEATHER)), StackIngredient.mergeStacked(Lists.newArrayList(StackIngredient.fromOre(5, "barkOak"), StackIngredient.fromOre(3, "barkSpruce"), StackIngredient.fromOre(2, "barkBirch"), StackIngredient.fromOre(4, "barkJungle"), StackIngredient.fromOre(8, "barkAcacia"), StackIngredient.fromOre(8, "barkDarkOak"), StackIngredient.fromOre(8, "barkBlood")))), ItemMaterial.getMaterial(ItemMaterial.EnumMaterial.TANNED_LEATHER));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(StackIngredient.fromStacks(ItemMaterial.getMaterial(ItemMaterial.EnumMaterial.SCOURED_LEATHER_CUT, 2)), StackIngredient.mergeStacked(Lists.newArrayList(StackIngredient.fromOre(5, "barkOak"), StackIngredient.fromOre(3, "barkSpruce"), StackIngredient.fromOre(2, "barkBirch"), StackIngredient.fromOre(4, "barkJungle"), StackIngredient.fromOre(8, "barkAcacia"), StackIngredient.fromOre(8, "barkDarkOak"), StackIngredient.fromOre(8, "barkBlood")))), ItemMaterial.getMaterial(ItemMaterial.EnumMaterial.TANNED_LEATHER_CUT, 2));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(new OreIngredient("dustSulfur"), new OreIngredient("dustSaltpeter"), new OreIngredient("dustCarbon")), new ItemStack(Items.GUNPOWDER, 2));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(StackIngredient.fromStacks(new ItemStack(Blocks.STICKY_PISTON, 4)), new OreIngredient("soap")), new ItemStack(Blocks.PISTON, 4));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromItem(Item.getItemFromBlock(Blocks.CACTUS))), new ItemStack(Items.DYE, 1, 2));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(StackIngredient.fromIngredient(8, new IngredientSpecial(stack -> stack.getItem() instanceof ItemFood)), new OreIngredient("dung")), Lists.newArrayList(new ItemStack(BWMItems.FERTILIZER, 8)));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(StackIngredient.fromStacks(ItemMaterial.getMaterial(ItemMaterial.EnumMaterial.SCOURED_LEATHER)), new OreIngredient("dung")), ItemMaterial.getMaterial(ItemMaterial.EnumMaterial.TANNED_LEATHER));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(StackIngredient.fromStacks(ItemMaterial.getMaterial(ItemMaterial.EnumMaterial.SCOURED_LEATHER_CUT, 2)), new OreIngredient("dung")), ItemMaterial.getMaterial(ItemMaterial.EnumMaterial.TANNED_LEATHER_CUT, 2));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(new OreIngredient("meatRotten")), new ItemStack(BWMItems.FERTILIZER, 1));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(new AdobeRecipe().getInputs(), new AdobeRecipe().getOutputs());
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 14))), new ItemStack(Blocks.WOOL, 8, 1));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 13))), new ItemStack(Blocks.WOOL, 8, 2));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 12))), new ItemStack(Blocks.WOOL, 8, 3));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 11))), new ItemStack(Blocks.WOOL, 8, 4));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 10))), new ItemStack(Blocks.WOOL, 8, 5));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 9))), new ItemStack(Blocks.WOOL, 8, 6));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 8))), new ItemStack(Blocks.WOOL, 8, 7));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 7))), new ItemStack(Blocks.WOOL, 8, 8));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 6))), new ItemStack(Blocks.WOOL, 8, 9));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 5))), new ItemStack(Blocks.WOOL, 8, 10));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 4))), new ItemStack(Blocks.WOOL, 8, 11));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 3))), new ItemStack(Blocks.WOOL, 8, 12));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 2))), new ItemStack(Blocks.WOOL, 8, 13));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 1))), new ItemStack(Blocks.WOOL, 8, 14));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 0))), new ItemStack(Blocks.WOOL, 8, 15));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 14))), new ItemStack(ModItems.WOOL, 32, 1));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 13))), new ItemStack(ModItems.WOOL, 32, 2));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 12))), new ItemStack(ModItems.WOOL, 32, 3));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 11))), new ItemStack(ModItems.WOOL, 32, 4));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 10))), new ItemStack(ModItems.WOOL, 32, 5));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 9))), new ItemStack(ModItems.WOOL, 32, 6));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 8))), new ItemStack(ModItems.WOOL, 32, 7));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 7))), new ItemStack(ModItems.WOOL, 32, 8));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 6))), new ItemStack(ModItems.WOOL, 32, 9));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 5))), new ItemStack(ModItems.WOOL, 32, 10));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 4))), new ItemStack(ModItems.WOOL, 32, 11));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 3))), new ItemStack(ModItems.WOOL, 32, 12));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 2))), new ItemStack(ModItems.WOOL, 32, 13));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 1))), new ItemStack(ModItems.WOOL, 32, 14));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 0))), new ItemStack(ModItems.WOOL, 32, 15));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(StackIngredient.mergeStacked(Lists.newArrayList(StackIngredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 1)), StackIngredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 2)), StackIngredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 3)), StackIngredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 4)), StackIngredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 5)), StackIngredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 6)), StackIngredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 7)), StackIngredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 8)), StackIngredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 9)), StackIngredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 10)), StackIngredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 11)), StackIngredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 12)), StackIngredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 13)), StackIngredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 14)), StackIngredient.fromStacks(new ItemStack(Blocks.WOOL, 8, 15)))), StackIngredient.fromStacks(new ItemStack(BWMItems.MATERIAL, 1, 21))), new ItemStack(Blocks.WOOL, 8, 0));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(StackIngredient.mergeStacked(Lists.newArrayList(StackIngredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 1)), StackIngredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 2)), StackIngredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 3)), StackIngredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 4)), StackIngredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 5)), StackIngredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 6)), StackIngredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 7)), StackIngredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 8)), StackIngredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 9)), StackIngredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 10)), StackIngredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 11)), StackIngredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 12)), StackIngredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 13)), StackIngredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 14)), StackIngredient.fromStacks(new ItemStack(ModItems.WOOL, 32, 15)))), StackIngredient.fromStacks(new ItemStack(BWMItems.MATERIAL, 1, 21))), new ItemStack(Blocks.WOOL, 32, 0));
        //BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(Items.BONE, 2)), Ingredient.fromStacks(new ItemStack(Items.DYE, 8, 15))), new ItemStack(ModItems.MATERIAL, 1, 5));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(ModItems.MATERIAL, 1, 1))), new ItemStack(ModItems.MATERIAL, 1, 2));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 2)), Ingredient.fromStacks(new ItemStack(BWMBlocks.URN, 1, 8)), Ingredient.fromStacks(new ItemStack(Blocks.DOUBLE_PLANT, 4, 5)), new OreIngredient("dung")), new ItemStack(ModBlocks.THORN_ROSE, 1, 0));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(ModItems.MATERIAL, 8, 1)), Ingredient.fromStacks(new ItemStack(ModItems.MATERIAL, 2, 3)), Ingredient.fromStacks(new ItemStack(Blocks.DOUBLE_PLANT, 4, 5)), new OreIngredient("dung")), new ItemStack(ModBlocks.THORN_ROSE, 1, 0));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(Items.DYE, 8, 1)), Ingredient.fromStacks(new ItemStack(Blocks.SAPLING, 1, 2)), Ingredient.fromStacks(new ItemStack(Items.ROTTEN_FLESH, 4)), Ingredient.fromStacks(new ItemStack(Items.WHEAT, 16))), new ItemStack(ModBlocks.LURETREE_SAPLING, 1, 0));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(ModItems.MATERIAL, 9, 5))), new ItemStack(ModItems.MATERIAL, 1, 2));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(ModItems.MATERIAL_DECO, 4, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 15))), new ItemStack(ModItems.MATERIAL_DECO, 4, 1));
        BWRegistry.CRUCIBLE.addUnstokedRecipe(Lists.newArrayList(Ingredient.fromStacks(new ItemStack(ModItems.MATERIAL_DECO, 4, 0)), Ingredient.fromStacks(new ItemStack(Items.DYE, 1, 0))), new ItemStack(ModItems.MATERIAL_DECO, 4, 2));
    }

    public static void unregisterUnusedRecipes() {
        mfrRemoveRecipes(Item.getItemFromBlock(BWMBlocks.BOOSTER));
        mfrRemoveRecipes(Item.getByNameOrId("betterwithmods:detector_rail_steel"));
        mfrRemoveRecipes(Item.getByNameOrId("betterwithmods:detector_rail_stone"));
        mfrRemoveRecipes(Item.getItemFromBlock(BWMBlocks.ANCHOR));
        mfrRemoveRecipes(Item.getByNameOrId("betterwithmods:rope"));
        mfrRemoveRecipes(Item.getByNameOrId("betterithmods:single_machine:0"));
        mfrRemoveRecipes(Item.getByNameOrId("betterithmods:single_machine:1"));
        mfrRemoveRecipes(Item.getByNameOrId("betterithmods:single_machine:2"));
        mfrRemoveRecipes(Item.getByNameOrId("betterithmods:single_machine:3"));

        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Items.GUNPOWDER, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.DONUT, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.MATERIAL, 1, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.MATERIAL, 1, 6)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.MATERIAL, 1, 12)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.MATERIAL, 1, 17)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.MATERIAL, 1, 19)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.MATERIAL, 1, 27)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.MATERIAL, 1, 28)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.MATERIAL, 1, 29)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.MATERIAL, 1, 32)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.MATERIAL, 1, 35)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMBlocks.NETHER_GROWTH, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Items.DYE, 1, 2)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMBlocks.AESTHETIC, 1, 0)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.PISTON, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMBlocks.BLOOD_SAPLING, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.FERTILIZER, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.WOOL, 1, 0)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.WOOL, 1, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.WOOL, 1, 2)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.WOOL, 1, 3)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.WOOL, 1, 4)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.WOOL, 1, 5)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.WOOL, 1, 6)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.WOOL, 1, 7)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.WOOL, 1, 8)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.WOOL, 1, 9)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.WOOL, 1, 10)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.WOOL, 1, 11)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.WOOL, 1, 12)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.WOOL, 1, 13)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.WOOL, 1, 14)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.WOOL, 1, 15)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMBlocks.AESTHETIC, 1, 11)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Items.COOKED_PORKCHOP, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Items.COOKED_BEEF, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.COOKED_BAT_WING, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.COOKED_OMELET, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Items.COOKED_CHICKEN, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.COOKED_SCRAMBLED_EGG, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.COOKED_WOLF_CHOP, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Items.COOKED_RABBIT, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.COOKED_MYSTERY_MEAT, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Items.COOKED_FISH, 1, 0)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Items.COOKED_FISH, 1, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.COOKED_KEBAB, 1, 0)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Items.COOKED_MUTTON, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.COOKED_EGG, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.CHOWDER, 2)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.CHOCOLATE, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Items.MUSHROOM_STEW, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.HEARTY_STEW, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.KIBBLE, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.MEATBALLS, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.COOKED_PUFFER, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.PREPARED_COOKED_PUFFER, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.COOKED_CLOWNFISH, 1)));

        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.MATERIAL_CONGEALED, 1, 0)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.MATERIAL_CONGEALED, 1, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.MATERIAL_CONGEALED, 1, 2)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.MATERIAL_CONGEALED, 1, 3)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.MATERIAL_CONGEALED, 1, 4)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.MATERIAL_CONGEALED, 1, 5)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(BWMItems.FERTILIZER, 8)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModBlocks.ADOBE, 1, 0)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.WOOL, 32, 0)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.WOOL, 32, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.WOOL, 32, 2)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.WOOL, 32, 3)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.WOOL, 32, 4)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.WOOL, 32, 5)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.WOOL, 32, 6)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.WOOL, 32, 7)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.WOOL, 32, 8)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.WOOL, 32, 9)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.WOOL, 32, 10)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.WOOL, 32, 11)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.WOOL, 32, 12)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.WOOL, 32, 13)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.WOOL, 32, 14)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.WOOL, 32, 15)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.MATERIAL, 1, 5)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.MATERIAL, 1, 2)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModBlocks.THORN_ROSE, 1, 0)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModBlocks.LURETREE_SAPLING, 1, 0)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.MATERIAL_DECO, 4, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(ModItems.MATERIAL_DECO, 4, 2)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.PLANKS, 1, 0), new ItemStack(Items.GLASS_BOTTLE, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.PLANKS, 1, 1), new ItemStack(Items.GLASS_BOTTLE, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.PLANKS, 1, 2), new ItemStack(Items.GLASS_BOTTLE, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.PLANKS, 1, 3), new ItemStack(Items.GLASS_BOTTLE, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.PLANKS, 1, 4), new ItemStack(Items.GLASS_BOTTLE, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Blocks.PLANKS, 1, 5), new ItemStack(Items.GLASS_BOTTLE, 1)));
        BWRegistry.CAULDRON.remove(Lists.newArrayList(new ItemStack(Items.CHORUS_FRUIT_POPPED, 1)));

        BWRegistry.MILLSTONE.remove(Lists.newArrayList(new ItemStack(BWMItems.MATERIAL, 1, 18), new ItemStack(BWMItems.MATERIAL, 1, 33), new ItemStack(BWMItems.MATERIAL, 1, 37), new ItemStack(BWMItems.MATERIAL, 1, 44)));

        BWRegistry.TURNTABLE.remove(Lists.newArrayList(new ItemStack(Items.CLAY_BALL, 1), new ItemStack(BWMBlocks.UNFIRED_POTTERY, 1, 0)));

        BWRegistry.KILN.remove(Lists.newArrayList(new ItemStack(BWMBlocks.UNFIRED_POTTERY, 1, 0), new ItemStack(BWMBlocks.RAW_PASTRY, 1, 0), new ItemStack(BWMBlocks.RAW_PASTRY, 1, 1), new ItemStack(BWMBlocks.RAW_PASTRY, 1, 2), new ItemStack(BWMBlocks.RAW_PASTRY, 1, 3), new ItemStack(BWMBlocks.RAW_PASTRY, 1, 4), new ItemStack(Blocks.IRON_ORE, 1), new ItemStack(Blocks.GOLD_ORE, 1), new ItemStack(Blocks.QUARTZ_ORE, 1)));

        //BetterWithAddons.removeCraftingRecipe(new ResourceLocation("betterwithmods/recipes/blocks/steel_anvil.json"));
    }

}
